import { StyleSheet } from 'react-native';

export const actividadScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  scrollView: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 10,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
  },
  section: {
    paddingHorizontal: 20,
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 15,
  },
  noServicesCard: {
    backgroundColor: '#f0f0f0',
    borderRadius: 12,
    padding: 20,
  },
  noServicesContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  noServicesText: {
    flex: 1,
  },
  noServicesTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
    marginBottom: 15,
    lineHeight: 22,
  },
  requestButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  requestButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginRight: 5,
  },
  noServicesIcon: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  clockIcon: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#f0f0f0',
    borderRadius: 12,
  },
  pastHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  filterButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#444',
    justifyContent: 'center',
    alignItems: 'center',
  },
  serviceCard: {
    backgroundColor: '#444',
    borderRadius: 12,
    overflow: 'hidden',
  },
  mapContainer: {
    height: 150,
    position: 'relative',
    backgroundColor: '#555',
  },
  mapImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  routeStart: {
    position: 'absolute',
    top: 20,
    left: 20,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#000',
  },
  routeEnd: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#000',
  },
  serviceInfo: {
    padding: 16,
  },
  serviceLocation: {
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 5,
  },
  serviceDateTime: {
    fontSize: 14,
    color: '#aaa',
    marginBottom: 5,
  },
  servicePrice: {
    fontSize: 16,
    fontWeight: '500',
    color: '#fff',
  },
  serviceActions: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingBottom: 16,
    gap: 12,
  },
  rateButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#333',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  rechargeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#333',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#fff',
    marginLeft: 6,
  },
});